apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-pagamento-config
data:
  APP_NAME: "ms-pagamento"
  APP_PORT: "8080"
  DB_URL: "jdbc:postgresql://postgres:5432/microservice"
  # URL interna do cluster Kubernetes. Se os outros MS tiverem nomes de service diferentes, ajuste aqui.
  MS_PEDIDO_HOST: "http://ms-pedido:8080"
  MS_PRODUCAO_HOST: "http://ms-producao:8080"