apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-pagamento-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-pagamento
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70