version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_microservice
    restart: always
    environment:
      POSTGRES_DB: microservice
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7774:7774"
    container_name: api-pagamento
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/microservice
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_PORT: 7774
      APP_NAME: api-pagamento
      MP_USER_ID: 2409646693
      MP_EXTERNAL_POS_ID: FIAP001POS
      MP_TOKEN: APP_USR-5511707722892084-042814-00c965a2a4ecf4475115062da61fb13d-2409646693

      entrypoint: >
        sh -c "java -jar
        -Dserver.port=${APP_PORT}
        -Dspring.datasource.url=${DB_URL}
        -Dspring.datasource.username=${DB_USERNAME}
        -Dspring.datasource.password=${DB_PASSWORD}
        ${APP_NAME}.jar"

volumes:
  pgdata: