apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento
  namespace: default
  labels:
    app: ms-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento
  template:
    metadata:
      labels:
        app: ms-pagamento
    spec:
      containers:
        - name: ms-pagamento-container
          image: REPLACE_ME_IMAGE_URL
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
          # Health Checks (Mantive os seus, estão ótimos)
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15

          env:
            # --- CONFIGURAÇÃO AWS (PERFEITA) ---
            - name: SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED
              value: "true"
            - name: AWS_REGION
              value: "us-east-1"
            
            # Credenciais para conectar na AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_session_token
            
            # Variáveis da Aplicação (Opcional, se precisar sobrescrever algo)
            - name: APP_PORT
              value: "8080"