apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pagamento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pagamento
  template:
    metadata:
      labels:
        app: ms-pagamento
    spec:
      # REMOVIDO: initContainers (não precisamos mais esperar o postgres local)
      
      containers:
        - name: ms-pagamento-container
          image: REPLACE_ME_IMAGE_URL # O pipeline substitui isso automaticamente
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
          
          # Carrega as variáveis (DB_URL, USER, PASS) injetadas pelo Pipeline
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
          
          # AQUI ESTÁ A CORREÇÃO DO ERRO:
          # ... (dentro de containers, logo após envFrom)
          env:
            # CORREÇÃO: Habilita o Secrets Manager para pegar DB_URL, Token MP, etc.
            - name: SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED
              value: "true" 
            - name: AWS_REGION
              value: "us-east-1"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15