name: Deploy ms-pagamento to EKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: fiap-eks-cluster
  ECR_REPOSITORY: fiap-app-ms-pagamento
  ECR_REGISTRY: 068504458505.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Constrói a imagem
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # Envia para o ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        # 1. Atualiza a imagem no manifesto de deployment
        sed -i 's|<IMAGE_URL_PLACEHOLDER>|${{ steps.build-image.outputs.image }}|g' k8s/app-deployment.yaml
        
        # 2. Deploy do Banco de Dados (Postgres Interno para o ms-pagamento)
        kubectl apply -f k8s/postgres-secret.yaml
        kubectl apply -f k8s/postgres-deployment.yaml

        # 3. Criação do Secret da Aplicação (Credenciais Mercado Pago e Banco)
        # Recria o secret para garantir atualização dos valores
        kubectl delete secret ms-pagamento-secret --ignore-not-found
        kubectl create secret generic ms-pagamento-secret \
          --from-literal=DB_USERNAME='root' \
          --from-literal=DB_PASSWORD='root' \
          --from-literal=MP_USER_ID='2409646693' \
          --from-literal=MP_EXTERNAL_POS_ID='FIAP001POS' \
          --from-literal=MP_TOKEN='APP_USR-5511707722892084-042814-00c965a2a4ecf4475115062da61fb13d-2409646693' \
          --dry-run=client -o yaml | kubectl apply -f -

        # 4. Aplica manifestos da Aplicação
        kubectl apply -f k8s/app-config.yaml
        kubectl apply -f k8s/app-deployment.yaml
        kubectl apply -f k8s/app-service.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Verify Deployment
      run: |
        echo "Aguardando rollout..."
        kubectl rollout status deployment/ms-pagamento || true
        kubectl get svc